### ISSUE TITLE
Hyprland Not Starting with Nvidia

### ISSUE THREAD

**Issue by angelgnz** [archcraft-os/archcraft-prime#2]
# Hyprland Not Starting with Nvidia
I faced some problems when first tried to start Hyprland and his is what worked for me.

To ensure that Hyprland starts correctly with Nvidia, follow these steps:

1. Install the necessary packages:
(Dont remember which ones were missing on my install. 
Also i replaced default nvidia with nvidia-dkms but didn't test the default)
```bash
yay -S nvidia-dkms qt5-wayland qt5ct libva
```

2. Create the missing `/etc/modprobe.d/nvidia.conf` file and add '/etc/modprobe.d/nvidia.conf' to it:

```bash
echo 'options nvidia-drm modeset=1' > /etc/modprobe.d/nvidia.conf
```

For more detailed instructions about Nvidia, refer to the [Hyprland Wiki](https://wiki.hyprland.org/hyprland-wiki/pages/Nvidia/).

3. If you're using a laptop or a PC with multiple GPUs, you might need to specify which GPU to use. Choose the appropriate option below based on your setup:

- For PC using a CPU with integrated graphics is recommended forcing Nvidia GPU usage, add the following line to the file `/usr/local/bin/run-hyprland` under the "## Nvidia Specific env variables" section:
  ```
  export WLR_DRM_DEVICES=/dev/dri/card0
  ```

- On my laptopt set first the integrated gpu and then the nvidia one:
  ```
  export WLR_DRM_DEVICES=/dev/dri/card1:/dev/dri/card0
  ```

```bash
## Nvidia Specific env variables
if [[ `lspci -k | grep -P 'VGA|3D|Display' | grep -w NVIDIA` ]]; then
    if [[ `lsmod | grep -w nvidia` ]]; then
        export GBM_BACKEND=nvidia-drm
        export __GLX_VENDOR_LIBRARY_NAME=nvidia
        export LIBVA_DRIVER_NAME=nvidia
        export WLR_NO_HARDWARE_CURSORS=1
        export WLR_DRM_DEVICES=/dev/dri/card1:/dev/dri/card0
    fi
fi
```
If you keep having problems comment out "export GBM_BACKEND=nvidia-drm"

For more detailed instructions about multi GPU, refer to the [Hyprland Wiki](https://wiki.hyprland.org/Configuring/Multi-GPU/).

Remember to save your changes and restart your system if necessary.

Edit: I'm not able to start none of the wayland compositors either but by now hyprland is amazing.

**Comment by adi1090x** [comment]
Use the Updated version.
